/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Resource = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'resourceType' : IDL.Text,
});
export const Career = IDL.Record({
  'id' : IDL.Text,
  'field' : IDL.Text,
  'roadmap' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'projects' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
  'resumeTips' : IDL.Vec(IDL.Text),
  'freeResources' : IDL.Vec(Resource),
  'jobOutlook' : IDL.Text,
  'salaryRange' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
});
export const ScholarshipProgram = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deadlineMonth' : IDL.Text,
  'coversLiving' : IDL.Bool,
  'eligibility' : IDL.Text,
  'applicationUrl' : IDL.Text,
  'coversTuition' : IDL.Bool,
  'fundingLevel' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'organization' : IDL.Text,
  'coversTravel' : IDL.Bool,
});
export const Country = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'overview' : IDL.Text,
  'continent' : IDL.Text,
  'programs' : IDL.Vec(ScholarshipProgram),
  'whyChoose' : IDL.Text,
});
export const QuizOption = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'keywords' : IDL.Vec(IDL.Text),
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});
export const CatalogResource = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCareers' : IDL.Func([], [IDL.Vec(Career)], ['query']),
  'getCareerById' : IDL.Func([IDL.Text], [IDL.Opt(Career)], ['query']),
  'getCareersByField' : IDL.Func([IDL.Text], [IDL.Vec(Career)], ['query']),
  'getCountries' : IDL.Func([], [IDL.Vec(Country)], ['query']),
  'getCountryById' : IDL.Func([IDL.Text], [IDL.Opt(Country)], ['query']),
  'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getResources' : IDL.Func([], [IDL.Vec(CatalogResource)], ['query']),
  'matchCareers' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Resource = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'resourceType' : IDL.Text,
  });
  const Career = IDL.Record({
    'id' : IDL.Text,
    'field' : IDL.Text,
    'roadmap' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'projects' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
    'resumeTips' : IDL.Vec(IDL.Text),
    'freeResources' : IDL.Vec(Resource),
    'jobOutlook' : IDL.Text,
    'salaryRange' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  const ScholarshipProgram = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deadlineMonth' : IDL.Text,
    'coversLiving' : IDL.Bool,
    'eligibility' : IDL.Text,
    'applicationUrl' : IDL.Text,
    'coversTuition' : IDL.Bool,
    'fundingLevel' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'organization' : IDL.Text,
    'coversTravel' : IDL.Bool,
  });
  const Country = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'overview' : IDL.Text,
    'continent' : IDL.Text,
    'programs' : IDL.Vec(ScholarshipProgram),
    'whyChoose' : IDL.Text,
  });
  const QuizOption = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'keywords' : IDL.Vec(IDL.Text),
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  const CatalogResource = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCareers' : IDL.Func([], [IDL.Vec(Career)], ['query']),
    'getCareerById' : IDL.Func([IDL.Text], [IDL.Opt(Career)], ['query']),
    'getCareersByField' : IDL.Func([IDL.Text], [IDL.Vec(Career)], ['query']),
    'getCountries' : IDL.Func([], [IDL.Vec(Country)], ['query']),
    'getCountryById' : IDL.Func([IDL.Text], [IDL.Opt(Country)], ['query']),
    'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getResources' : IDL.Func([], [IDL.Vec(CatalogResource)], ['query']),
    'matchCareers' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };