/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Career {
  'id' : string,
  'field' : string,
  'roadmap' : Array<string>,
  'title' : string,
  'projects' : Array<string>,
  'description' : string,
  'keywords' : Array<string>,
  'resumeTips' : Array<string>,
  'freeResources' : Array<Resource>,
  'jobOutlook' : string,
  'salaryRange' : string,
  'requiredSkills' : Array<string>,
}
export interface CatalogResource {
  'url' : string,
  'title' : string,
  'description' : string,
  'category' : string,
}
export interface Country {
  'id' : string,
  'name' : string,
  'overview' : string,
  'continent' : string,
  'programs' : Array<ScholarshipProgram>,
  'whyChoose' : string,
}
export interface QuizOption {
  'id' : bigint,
  'text' : string,
  'keywords' : Array<string>,
}
export interface QuizQuestion {
  'id' : bigint,
  'question' : string,
  'options' : Array<QuizOption>,
}
export interface Resource {
  'url' : string,
  'title' : string,
  'resourceType' : string,
}
export interface ScholarshipProgram {
  'name' : string,
  'description' : string,
  'deadlineMonth' : string,
  'coversLiving' : boolean,
  'eligibility' : string,
  'applicationUrl' : string,
  'coversTuition' : boolean,
  'fundingLevel' : string,
  'benefits' : Array<string>,
  'organization' : string,
  'coversTravel' : boolean,
}
export interface _SERVICE {
  'getAllCareers' : ActorMethod<[], Array<Career>>,
  'getCareerById' : ActorMethod<[string], [] | [Career]>,
  'getCareersByField' : ActorMethod<[string], Array<Career>>,
  'getCountries' : ActorMethod<[], Array<Country>>,
  'getCountryById' : ActorMethod<[string], [] | [Country]>,
  'getQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getResources' : ActorMethod<[], Array<CatalogResource>>,
  'matchCareers' : ActorMethod<[Array<bigint>], Array<string>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];