/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuizQuestion {
    id: bigint;
    question: string;
    options: Array<QuizOption>;
}
export interface Resource {
    url: string;
    title: string;
    resourceType: string;
}
export interface ScholarshipProgram {
    name: string;
    description: string;
    deadlineMonth: string;
    coversLiving: boolean;
    eligibility: string;
    applicationUrl: string;
    coversTuition: boolean;
    fundingLevel: string;
    benefits: Array<string>;
    organization: string;
    coversTravel: boolean;
}
export interface Career {
    id: string;
    field: string;
    roadmap: Array<string>;
    title: string;
    projects: Array<string>;
    description: string;
    keywords: Array<string>;
    resumeTips: Array<string>;
    freeResources: Array<Resource>;
    jobOutlook: string;
    salaryRange: string;
    requiredSkills: Array<string>;
}
export interface QuizOption {
    id: bigint;
    text: string;
    keywords: Array<string>;
}
export interface Country {
    id: string;
    name: string;
    overview: string;
    continent: string;
    programs: Array<ScholarshipProgram>;
    whyChoose: string;
}
export interface CatalogResource {
    url: string;
    title: string;
    description: string;
    category: string;
}
export interface backendInterface {
    getAllCareers(): Promise<Array<Career>>;
    getCareerById(id: string): Promise<Career | null>;
    getCareersByField(field: string): Promise<Array<Career>>;
    getCountries(): Promise<Array<Country>>;
    getCountryById(id: string): Promise<Country | null>;
    getQuizQuestions(): Promise<Array<QuizQuestion>>;
    getResources(): Promise<Array<CatalogResource>>;
    matchCareers(answers: Array<bigint>): Promise<Array<string>>;
}
import type { Career as _Career, Country as _Country } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllCareers(): Promise<Array<Career>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCareers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCareers();
            return result;
        }
    }
    async getCareerById(arg0: string): Promise<Career | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareerById(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareerById(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCareersByField(arg0: string): Promise<Array<Career>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareersByField(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareersByField(arg0);
            return result;
        }
    }
    async getCountries(): Promise<Array<Country>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCountries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCountries();
            return result;
        }
    }
    async getCountryById(arg0: string): Promise<Country | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCountryById(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCountryById(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestions(): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions();
            return result;
        }
    }
    async getResources(): Promise<Array<CatalogResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResources();
            return result;
        }
    }
    async matchCareers(arg0: Array<bigint>): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.matchCareers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.matchCareers(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Career]): Career | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Country]): Country | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
